feat(config): Merge in header/footer MFE runtime configuration changes.
Received an error with webpack concerning the following.
```
Error: PostCSS plugin postcss-discard-comments requires PostCSS 8.
```

More details here.
https://discuss.openedx.org/t/gradebook-mfe-npm-run-build-postcss-plugin-postcss-discard-comments-requires-postcss-8/8630

To resolve this we chose not to import the following dependency and stay with the current version that edX supplied.
```
"devDependencies": {
    "@edx/frontend-build": "npm:@cucwd-prod/frontend-build@9.0.5-maple.3",
}
```